package:
  name: aws-sdk-cpp
  version: "1.11.591"
  epoch: 0
  description: "The AWS SDK for C++"
  copyright:
    - license: Apache-2.0

environment:
  contents:
    packages:
      - aws-crt-cpp-dev
      - zlib-dev
      - curl-dev
      - build-base
      - busybox
      - ca-certificates-bundle
      - cmake
      - samurai

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/aws/aws-sdk-cpp
      tag: ${{package.version}}
      expected-commit: c051e364cae2361477f6b39f4077984257ff5976

  - uses: cmake/configure
    with:
      opts: |
        -DBUILD_SHARED_LIBS=True \
        -DCMAKE_BUILD_TYPE=None \
        -DBUILD_DEPS=OFF \
        -DBUILD_TESTING=OFF \
        -DCMAKE_SYSTEM_NAME=Linux \
        -DCMAKE_HOST_SYSTEM_NAME=Linux

  - uses: cmake/build

  - uses: cmake/install

  - uses: strip

subpackages:
  - name: aws-sdk-cpp-dev
    description: aws-sdk-cpp dev
    pipeline:
      - uses: split/dev
    dependencies:
      runtime:
        - aws-crt-cpp-dev

update:
  enabled: true
  github:
    identifier: aws/aws-sdk-cpp
    use-tag: true

test:
  pipeline:
    - uses: test/tw/ldd-check
